### PR TITLE
Py3k

### PR DESCRIPTION
**Pull request by jtharris**
This was the minimum changes to get this running with Python 3.4.  The tests run but are failing currently, but I think that is because the data there is dependent on the Avalara account (our account isn't set up for WA).

### CODE REVIEW

**Comment by jobelenus** [comment]
Justin,

Thanks for the request. I'm not sure how quickly I'll be able to get to this, but hopefully later this week. I do want to make sure that this doesn't create any problems running on python 2.x. If I find any I will let you know.

**Comment by jobelenus** [comment]
A quick note for working with the avalara integration. I absolutely recommend creating a second "Company" (in their parlance) that is specifically for Testing (they support this and you can mark that company as a test company so it doesn't count against your account). They walk you through a few set up steps and eventually you set up the Nexus rules. After selecting US, you get to go to states. I took a screenshot (see attached) of how ours looks. Then the tax check against WA in the test cases should work for you. I am noticing that some of the tests are failing some internal checks though, so I am also looking into the cause of that. And then I'll be onto checking out your pull request.
screen shot 2015-03-05 at 6 03 09 pm

**Comment by jobelenus** [comment]
While your changes work on python3.X they are obviously broken for python2.X. It is important to have the same codebase for either version of python. So, I cannot merge this pull request as is. I would ask that you commit additional changes such that the same codebase passes tests on both python2.X and 3.X

**Comment by jobelenus** [comment]
Checked out great (my env was giving me trouble). Merged and pushed. I will be creating a new release through PyPi for this as well, but the codebase is up to date for you!

**Comment by jtharris** [comment]
Thanks, John!  Would you mind giving me a ping when it lands in PyPi?

**Comment by jobelenus** [comment]
OK -- 1.2 release is up on git and pypi (
https://pypi.python.org/pypi/PyAvaTax)

**Comment by jtharris** [comment]
Awesome - very much appreciated.

**Pull request merged**
