### PR TITLE
Rename get_query_set methods to get_queryset to prevent RemovedInDjango18Warning.

### PR DESCRIPTION
**Pull request by kaofelix**

### CODE REVIEW

**Comment by jobelenus** [comment]
Sorry, I haven't been able to get to this yet -- but I will soon!

**Comment by kaofelix** [comment]
Hey, no worries!

**Comment by kaofelix** [comment]
Sorry, closed by mistake...

**Comment by kaofelix** [comment]
No worries! Let me know if you need any more info. Closed the PR by mistake while writing the comment, sorry :)

**Comment by jobelenus** [comment]
I'm making this release 1.3 now.

**Comment by kaofelix** [comment]
Thanks!

**Pull request merged**
