### PR TITLE
[FIX] Guard Django import in core

### PR DESCRIPTION
**Pull request by lasley**
* Django assets are being imported in base, which enforces a dependency that is not supposed to be required. Add an import guard for `get_django_recorder` and a check before using it

### CODE REVIEW

**Comment by jobelenus** [comment]
This commit shouldn't be necessary. The `django_integration.py` already catches an ImportError.

**Comment by lasley** [comment]
Hi @jobelenus - that doesn't seem to be the case in 1.3.9

```
from pyavatax.api import API
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/dlasley/Documents/Repos/oca-l10n-usa/env/lib/python2.7/site-packages/pyavatax/api.py", line 3, in <module>
    from pyavatax.base import Document, Address, BaseResponse, BaseAPI, AvalaraException, AvalaraTypeException, AvalaraValidationException, AvalaraServerException, ErrorResponse, AvalaraServerNotReachableException
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/dlasley/Documents/Repos/oca-l10n-usa/env/lib/python2.7/site-packages/pyavatax/base.py", line 7, in <module>
    from pyavatax.django_integration import get_django_recorder
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/dlasley/Documents/Repos/oca-l10n-usa/env/lib/python2.7/site-packages/pyavatax/django_integration.py", line 1, in <module>
    from django.utils import timezone
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: No module named django.utils

```

**Comment by jobelenus** [comment]
Thank you for finding this. I made a fix and released 1.3.10. Let me know if that works for you and I will close this PR.

**Comment by lasley** [comment]
The new version works, thanks @jobelenus

**Pull request closed without merging**
